# .github/workflows/firebase-deploy.yml

name: Deploy Frontend to Firebase

on:
  push:
    branches:
      - main # This workflow runs on pushes to the main branch

jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and Build Frontend
        run: cd client && npm install && npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_OFFICE_GPT_PROD }}' # Make sure this secret name is correct
          projectId: office-gpt-prod
          channelId: live
